export let products = [
  {
    title: "bose headset",
    image: "./images/headphones.jpg",
    price: "$499.99",
    category: "Men",
    stars: "./images/Star.png",
    size: "M",
    button: "ADD IN CART",
    color: "black",
  },
  {
    title: "Sony Headset",
    image: "./images/headphones2.jpeg",
    price: "$799.99",
    category: "Women",
    stars: "./images/Star.png",
    size: "L",
    button: "ADD IN CART",
    color: "gray",
  },
  {
    title: "Apple headset",
    image: "./images/headphones3.jpg",
    price: "$399.99",
    category: "Kids",
    stars: "./images/Star.png",
    size: "S",
    button: "ADD IN CART",
    color: "white",
  },
  {
    title: "Gaming headset",
    image: "./images/headphones4.jpg",
    price: "$999.99",
    category: "Kids",
    stars: "./images/Star.png",
    size: "M",
    button: "ADD IN CART",
    color: "colorfull",
  },
  // {
  //   title: "Product five",
  //   image: "./images/product5.jpeg",
  //   price: "400$",
  //   category: "Men",
  //   size: "s",
  // },
  // {
  //   title: "Product six",
  //   image: "./images/product6.jpeg",
  //   price: "100$",
  //   category: "Men",
  //   size: "s",
  // },
];

export let products_2 = [
  {
    title: "Qualcomm Earphones",
    image: "./images/Qualcomm Earphones.jpg",
    price: "59.99",
    category: "Men",
    stars: "./images/Star.png",
    size: "M",
    button: "ADD IN CART",
  },
  {
    title: "Stereo Earphones",
    image: "./images/Stereo Earphones.jpg",
    price: "39.99",
    category: "Women",
    stars: "./images/Star.png",
    size: "L",
    button: "ADD IN CART",
  },
  {
    title: "Samsung EarBuds",
    image: "./images/Samsung Earphones.jpg",
    price: "79.99",
    category: "Kids",
    stars: "./images/Star.png",
    size: "S",
    button: "ADD IN CART",
  },
  {
    title: "Airpods",
    image: "./images/Airpods.jpg",
    price: "99.99",
    category: "Kids",
    stars: "./images/Star.png",
    size: "M",
    button: "ADD IN CART",
  },
  // {
  //   title: "Product five",
  //   image: "./images/product5.jpeg",
  //   price: "400$",
  //   category: "Men",
  //   size: "s",
  // },
  // {
  //   title: "Product six",
  //   image: "./images/product6.jpeg",
  //   price: "100$",
  //   category: "Men",
  //   size: "s",
  // },
];